---
- name: Initial Updates
  hosts: all
  tasks:
    - name: Package Update and Upgrades
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Display stats of Update & Upgrades
      debug:
        msg: "{{updatesys.stdout_lines|last}}"
