---
- name: Configuring second NIC
  hosts: all
  vars:
     target_mac: "76:D3:BA:30:24:15"
     network_connection:
          -  name: eth1
             type: ethernet
             mac: "{{ target_mac }}"
             state:
             ip :
               dhcp: no
               address:
                    -  10.100.11.150/24
